const rules = {
	'block-no-empty': true,
	'color-no-invalid-hex': true,
	'comment-no-empty': true,
	'declaration-block-no-duplicate-properties': [ true, { ignore: [ 'consecutive-duplicates-with-different-values' ] } ],
	'declaration-block-no-shorthand-property-overrides': true,
	'font-family-no-duplicate-names': true,
	'font-family-no-missing-generic-family-keyword': true,
	'function-calc-no-unspaced-operator': true,
	'function-linear-gradient-no-nonstandard-direction': true,
	'keyframe-declaration-no-important': true,
	'media-feature-name-no-unknown': true,
	'no-duplicate-at-import-rules': true,
	'no-duplicate-selectors': true,
	'no-empty-source': true,
	'stylistic/no-extra-semicolons': true,
	'no-invalid-double-slash-comments': true,
	'property-no-unknown': true,
	'selector-pseudo-class-no-unknown': true,
	'selector-pseudo-element-no-unknown': true,
	'selector-type-no-unknown': true,
	'string-no-newline': true,
	'unit-no-unknown': true,

	'number-max-precision': 3,
	'declaration-block-single-line-max-declarations': 1,
	'stylistic/selector-max-empty-lines': 0,
	'selector-max-universal': 2,
	'no-unknown-animations': true,

	'stylistic/color-hex-case': 'lower',
	'font-family-name-quotes': 'always-where-recommended',
	'stylistic/function-comma-space-after': 'always',
	'stylistic/function-comma-space-before': 'never',
	'stylistic/function-max-empty-lines': 0,
	'stylistic/function-parentheses-space-inside': 'never',
	'stylistic/function-whitespace-after': 'always',
	'stylistic/number-leading-zero': 'always',
	'stylistic/number-no-trailing-zeros': true,
	'stylistic/string-quotes': 'single',
	'length-zero-no-unit': true,
	'stylistic/unit-case': 'lower',
	'value-keyword-case': [
		'lower',
		{
			camelCaseSvgKeywords: true,
		},
	],
	'stylistic/value-list-comma-space-after': 'always',
	'stylistic/value-list-comma-space-before': 'never',
	'stylistic/value-list-max-empty-lines': 0,
	'stylistic/property-case': 'lower',
	'stylistic/declaration-bang-space-after': 'never',
	'stylistic/declaration-bang-space-before': 'always',
	'stylistic/declaration-colon-space-after': 'always',
	'stylistic/declaration-colon-space-before': 'never',
	'stylistic/declaration-block-semicolon-newline-after': 'always',
	'stylistic/declaration-block-semicolon-space-after': 'always-single-line',
	'stylistic/declaration-block-semicolon-space-before': 'never',
	'stylistic/declaration-block-trailing-semicolon': 'always',
	'stylistic/block-closing-brace-newline-after': 'always',
	'stylistic/block-closing-brace-newline-before': 'always-multi-line',
	'stylistic/block-opening-brace-space-before': 'always',
	'stylistic/selector-attribute-brackets-space-inside': 'never',
	'stylistic/selector-attribute-operator-space-after': 'never',
	'stylistic/selector-attribute-operator-space-before': 'never',
	'selector-attribute-quotes': 'always',
	'stylistic/selector-combinator-space-after': 'always',
	'stylistic/selector-combinator-space-before': 'always',
	'stylistic/selector-descendant-combinator-no-non-space': true,
	'stylistic/selector-pseudo-class-case': 'lower',
	'stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
	'stylistic/selector-pseudo-element-case': 'lower',
	'selector-type-case': 'lower',
	'stylistic/selector-list-comma-newline-before': 'never-multi-line',
	'stylistic/selector-list-comma-newline-after': 'always',
	'stylistic/media-feature-colon-space-after': 'always',
	'stylistic/media-feature-colon-space-before': 'never',
	'stylistic/media-feature-name-case': 'lower',
	'stylistic/media-feature-parentheses-space-inside': 'never',
	'stylistic/media-feature-range-operator-space-after': 'always',
	'stylistic/media-feature-range-operator-space-before': 'always',
	'stylistic/media-query-list-comma-space-after': 'always',
	'stylistic/media-query-list-comma-space-before': 'never',
	'stylistic/at-rule-name-case': 'lower',
	'stylistic/at-rule-name-space-after': 'always',
	'stylistic/at-rule-semicolon-newline-after': 'always',
	'stylistic/at-rule-semicolon-space-before': 'never',
	'comment-whitespace-inside': 'always',

	'stylistic/indentation': 'tab',
	'stylistic/linebreaks': 'unix',
	'stylistic/max-empty-lines': 3,
	'stylistic/no-eol-whitespace': true,
	'stylistic/no-missing-end-of-source-newline': true,
	'stylistic/no-empty-first-line': true,

	'order/order': [
		[],
		{ severity: 'warning' },
	],
};

module.exports = rules;
